name: Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare build environment
        run: |
          pacman -Syu --noconfirm base-devel git curl pacman-contrib sudo
          useradd -m ashkore
          echo "ashkore ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          mkdir -p /build
          chown -R ashkore:ashkore /build

      - name: Build AUR packages
        run: |
          sudo -u ashkore bash <<'EOF'
          set -e
          cd /build
          mkdir aur-build && cd aur-build

          PKGS=(manjaro-asian-input-support v2rayn-bin)

          for pkg in "${PKGS[@]}"; do
            git clone https://aur.archlinux.org/${pkg}.git
            cd ${pkg}
            makepkg -sf --noconfirm
            mv *.pkg.tar.zst ../
            cd ..
          done

          cd ..
          mkdir repo
          mv aur-build/*.pkg.tar.zst repo/
          cd repo
          repo-add ashkorehennessy.db.tar.gz *.pkg.tar.zst
          ln -sf ashkorehennessy.db.tar.gz ashkorehennessy.db
          ln -sf ashkorehennessy.files.tar.gz ashkorehennessy.files
          EOF

      - name: Install OSSUTIL
        run: |
          curl -o ossutil64 https://gosspublic.alicdn.com/ossutil/1.7.17/ossutil64
          chmod +x ossutil64
          sudo mv ossutil64 /usr/local/bin/ossutil64

      - name: Configure OSSUTIL
        run: |
          ossutil64 config \
            -e ${{ secrets.OSS_ENDPOINT }} \
            -i ${{ secrets.OSS_ACCESS_KEY_ID }} \
            -k ${{ secrets.OSS_ACCESS_KEY_SECRET }} \
            -L CH

      - name: Upload repo to OSS
        run: |
          ossutil64 cp ./arch-install.sh oss://${{ secrets.OSS_BUCKET }}/ --update
          ossutil64 cp ./postinstall.sh oss://${{ secrets.OSS_BUCKET }}/ --update
          ossutil64 rm oss://${{ secrets.OSS_BUCKET }}/ashkorehennessy/ -r -f || true
          ossutil64 cp -r /build/repo oss://${{ secrets.OSS_BUCKET }}/ashkorehennessy/ --update
